### ISSUE TITLE
Morphman does not seem to work with qt5

### ISSUE THREAD

**Issue by flygplan1** [kaegi/MorphMan#291] opened 2023-07-06 15:05 UTC
Got this error message when starting anki with morphman the first time:
"Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨MorphMan for Anki 21⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\jonlundb\AppData\Roaming\Anki2\addons21\900801631\__init__.py", line 2, in <module>
    from PyQt6.QtWidgets import *
ModuleNotFoundError: No module named 'PyQt6'"

⁩

**Comment by CodeWithMa** [comment] 2023-07-06 16:51
Duplicate of #286

**Closed** 2023-08-17 14:54 UTC
