### ISSUE TITLE
Identical morphemes aren't skipped if they don't have brackets/don't match exactly

### ISSUE THREAD

**Issue by weirdalsuperfan** [kaegi/MorphMan#45] opened 2019-10-03 17:07 UTC
I use the MIA Japanese addon to add accent information in brackets to the cards I wanted to review, while not touching the ones I didn't want to review. I do this editing in the browser. Since I generally just pick the first card I see with a word I want to learn, I skip over other identical words since it's too much work to delete them.

Before, morphman would automatically skip cards with identical focus morphs. However, I just came across a card with an otherwise identical morph to one I had just reviewed but with no brackets (because it was one I intended to have automatically skipped). When I went into the browser and generated accent info for that card as well, upon returning to the reviewer the card immediately went away, leading me to guess that the cards need to have exactly the same stuff in their focus morph field for this to work.

I'd like the skip identical morph functionality to work after brackets have been accounted for.

**Comment by weirdalsuperfan** [comment] 2019-10-05 06:40
@InfiniteRain

**Comment by InfiniteRain** [comment] 2019-10-05 17:53
You're reporting on the wrong repo bro, the 2.1 version one is here:
https://github.com/landonepps/MorphMan21

**Comment by shanrauf** [comment] 2019-10-06 01:46
@InfiniteRain Landon's branch was merged back into this branch - future PR's and issues should go here

**Comment by weirdalsuperfan** [comment] 2019-10-06 07:46
Related, but possibly requires its own issue (lmk): It seems like when morphman recalc regenerates the Focus morph it clears any brackets. Being able to have those brackets saves me from using an extra field to view info on the Focus morph (the same reason I/some other guy reported the bug about morphman clearing known Focus morphs - so that I didn't have to copy the morph to another field). Specifically, I myself use the Focus field to view the focus morph's stroke order, as well as accent info (what I need the brackets for). Currently I have to regenerate those brackets after each recalc (i.e. every day). Only just realized the cause of the problem, though.

@InfiniteRain I actually accidentally thought that too and initially opened this issue there before noticing it'd been merged back into this repo.

**Comment by InfiniteRain** [comment] 2019-10-06 08:51
Whoops, my bad. Didn't realize that this got merged with the main repo. In any case, I will try to look into this when I can.

**Comment by InfiniteRain** [comment] 2019-10-06 08:59
Just to be sure, do you have the following option enabled?
 
![image](https://user-images.githubusercontent.com/19305779/66266659-a7097580-e830-11e9-878e-862a81836dc9.png)

**Comment by weirdalsuperfan** [comment] 2019-10-06 16:42
Yeah, I double checked just now and it's enabled.

**Comment by weirdalsuperfan** [comment] 2019-10-12 13:32
Anyone working on this? It makes the whole "ignore everything contained within brackets" thing kinda useless, and idk if I can trust morphman to give me new words anymore while this problem exists

**Comment by InfiniteRain** [comment] 2019-10-12 17:13
Okay, I took a look into this. The identification of morphs with the setting turned on seems to be correct. I made a test card with a test sentence, and ran three tests: 

1. Furigana IS NOT generated, option to skip the brackets IS NOT turned on: resulted in K15/V15.
2. Furigana IS generated, option to skip the brackets IS NOT turned on. Resulted in K17/V20.
3. Furigana IS generated, option to skip the brackets IS turned on. Resulted in K15/V15.

It looks like the problem you're describing applies only when MorphMan is selecting which cards to skip. Other than that, the generated K/V values seem to be correct, so that means you can trust the K/V values at least. The database also seems to be correct. 

Could you please provide exact steps to recreate the bug? Create a new profile and make the bug happen, tell me exactly what sentence you used and what steps you took.

**Comment by weirdalsuperfan** [comment] 2019-10-12 19:12
Thanks for taking up the issue. Really it's not hard to recreate the bug, but I made a whole new profile and set up morphman again just so I could explain it all over again....and in the process found a 3rd bug (the 2nd one being the problem of bracketed stuff being deleted from the Focus field on recalc).

1. Create a new profile (make sure you have MIA japanese and morphman. I also have other stuff like the old japanese support addon)
2. X-out of/cancel any errors MIA gives you, then restart anki to be safe
3. X-out of/cancel any errors MIA gives you
4. Make a new deck called test.
5. Make a new card type called japanese
6. Add the field "Focus" to japanese. Make sure it has at least "Focus" and "Expression" as fields.
7. Go into morphman preferences and delete the 2nd note type in the note filter. Also change the 1st filter to only work on japanese. Also delete the japanese tag requirement. Double check that it works on Expression and modifies the cards (these should be set by default).
8. Under the extra fields tab change the focus morph field to Focus
9. Under tags make a note of the already known tag. In my haste to make this I renamed it iknowthis
10. Check off all the boxes under General
11. Create the following cards as japanese notes and add them to the Test deck:
11a. Expression: 住んでいるからだね
Focus (for good measure): 住む
tag (just put w/e your known morph tag is like mm_alreadyKnown): iknowthis
11b. Expression: 昔から住んでいる
Also press F2 in the expression field for this card to generate readings/accents (doesn't matter if you do it for none of them or all of them, but I happened to do this on a whim). Make sure this card doesn't have the mm_alreadyKnowntag (it might've gotten carried over from when you created the last note, so remove it).
11c. Expression: 昔住んでいるね
12. Run morphman recalc
13. Look at the results. both 11b and 11c should have 昔 as the focus morph and mm_vocab somewhere in the tags. 11a should be a comprehension card.
14. Now select the Focus field of 11b and and press F2 to generate accents/readings for the Focus morph itself. Repeat for 11c AND also for 11a.
15. Rereun morphman recalc.
16. You'll notice that 11a's focus morph wasn't modified (which is expected behavior), and also its accent/reading info wasn't either (!). However, both 昔's had their bracketed stuff removed. This is one bug. This implies to me that the bracket functionality comes after the check to totally ignore Focus morph fields (brackets or otherwise) for cards tagged as alreadyknown.
17. For the more major bug, go to the Focus morph of JUST 11b now, and press F2 to generate readings/accents. By the way, your K/V values should be 6 right now.
17b. Since I do this in my normal profile, just to be safe, go to the options for the Test deck and set the learning steps for both new cards and lapses to just "1" instead of the defaults of 1 10 and 10.
18. You should have noticed in step 13 that you only have 2 new cards, because one of your 3 cards is a comprehension card. Now go learn those cards in the reviewer (due to a weird bug in either anki or with my plugins, the number of new cards displayed in this new profile doesn't seem to update immediately...so sometimes it said 3 or something even though if I went into the reviewer and immediately exited it turned into 2, even though the card that was up for learning (11b) didn't change).
19. On the first card, press k.
20. Observe that the second card still comes up. This is the other bug. (you'll notice that you have 2 reviews if you keep going, but they're both this card)

At this point, the bugs should have manifested themselves, but they seem to partially go away if you run morphman recalc (I think because it changes vocab cards to fresh cards). However, that's impractical in the middle of a review session when you can't be expected to know or card how often you'll run into a card with duplicates waiting. Also, you shouldn't have to recalc even once in the middle of the session.

20b. Anyway, for the sake of this experiment, go into the browser and unsuspend card 11b, since it should have been suspended by morphman when you pressed k.

21. Also in the browser, remove the newly automatically added iknowthis tag from card 11b (and note that the tag hasn't been added to 11c).
22. Run morphman recalc
23. Add accent/reading info to both 11b and 11c's Focus fields.
24. Make sure you still have the same 2 new cards, and then go learn them in the reviewer
25. Observe that your deck is now empty. This is an even stranger 3rd bug that I encountered in making this step-by-step reproduction guide.
26. Go into your browser and unsuspend both cards. Notice that their tags haven't changed.
27. Remove the accent/reading information from the Focus field for both cards (if you only remove it for one, you'll just end up back at step 17).
28. Go learn your new cards. You'll notice that they both show up now. This implies something is seriously wrong with how brackets/Focus morphs with brackets for vocab cards (1T cards) are treated.

**Comment by InfiniteRain** [comment] 2019-10-13 06:22
I will take a look into tracking down the issue in the next few days. Thank you for the detailed write-up. I have never come across this bug because I use morphman strictly for the K/V checks, but not for sorting/finding 1T sentences. Either way the bug is very annoying and should be fixed. I hope that I will have time to do it during the week.

**Comment by weirdalsuperfan** [comment] 2019-10-14 11:12
Thanks. I'll leave it to you. In the meantime I guess I won't add accent info to my focus morphs, to be safe. That last bug really spooked me.

**Comment by weirdalsuperfan** [comment] 2019-10-15 16:19
Hm, morphman is giving me 1T cards for words I already know - specifically, words whose focus morph field has brackets. This means it's putting some weird stuff in my database and it's losing its reliability. Update: Bulk removing readings from the focus field increased my K value.

**Comment by InfiniteRain** [comment] 2019-10-15 17:55
That is very weird. Modifying the focus field (as far as my knowledge of MorphMan goes), should not affect K/V values at all. As for why it gives you 1T sentences for words with modified focus field, I think it's because the bracket check is applied to the expression field and not the focus field. In any case, focus field is autogenerated and should not be touched at all. As for why it modifies the K/V values, it's a complete mistery to me. Although, I do know that K/V value display tends to get bugged out after a massive recalc. For example, when I did DB tests the other day, the K/V display didn't reflect the amount of actual morphs in the known.db, even though the DB was generated correctly.

**Comment by InfiniteRain** [comment] 2019-10-16 14:03
I'm extremely short on time, I think I won't be able to look into this until at least next week. This bug, while having an annoying workaround, does need to be fixed. If anyone else has time to look into this, then this would be much appreciated. If not, then this will have to wait until next week.

@shanrauf

**Comment by InfiniteRain** [comment] 2019-10-21 12:52
@weirdalsuperfan 
Sorry for the delay, I took a look into everything as well as tried recreating the bug. Here's what I found.

> However, both 昔's had their bracketed stuff removed. This is one bug. This implies to me that the bracket functionality comes after the check to totally ignore Focus morph fields (brackets or otherwise) for cards tagged as alreadyknown.

This is not a bug, this is expected behaviour of MorphMan. Focus field gets regenerated for every card that is new during the recalc procedure. That field serves as a reference point for MorphMan's sorting process. It chooses cards to skip/show based on what the word is in the field. Here's how it works: it checks the focus field against your database, and then if the contents of the focus field are present in the database, then the card gets skipped. My check only applies to recalc procedure for the expression field. Before calculating morphs from the expression field, it removes all the brackets, which in turn results in a correctly-generated database. However, you mentioned that you generate furigana for your focus field.  You should not do that. Focus field should never be changed by the user at all. The reason for why it didn't skip the known morph, is because it was checking the bracketed version of the focus field instead of the version without brackets, hence it thought that you didn't know the morph. So if you remove all the brackets from all the focus fields on the new (and probably old as well) cards, then the issue should go away. 

There's probably a way to make it remove all the brackets from the focus field before choosing what to show/skip/sort, but that has an implication of resulting with issues that are a lot more major. The whole code base of MorphMan is, frankly, shit; it's without tests and without proper structure/standards. So it's not worth the risk.

Here's a potential work around for your use case: make a new field call it something like "Vocab" and with each new card just copy the contents from the focus field into there and use it to generate furigana. Leave the original focus field absolutely untouched. There could probably be a plugin made for this.

**Comment by weirdalsuperfan** [comment] 2019-10-21 13:53
Thanks for looking into it. I have a suggested fix I'd like you to consider.

You probably know about the fix that @shanrauf made a while back that stops focus morphs from being deleted from already learned cards. This fix was done precisely because people had needed to duplicate the focus field, which is just redundant. The fix should have addressed that problem, but it evidently hasn't. I don't think the behavior or fix you described makes sense. I can understand your unwillingness to fix it, but I wouldn't call it expected behavior. Expectation derives solely from the user. And as it stands, the inconvenience of the focus field being cleared still exists, so at this point it would seem that shan's fix was pretty useless - which I'd like not to think. I'd like to think the intention to fix the problem of having to copy the focus field is the true purpose of that fix, which means it's an incomplete fix.

I think it would make more sense for morphman itself to provide the functionality for such a field that it generates once and doesn't change. Having to constantly go through the extra step of copying the focus field of new cards (even in bulk) is not what automation should be for. Just allowing the user to specify an additional special field that gets a duplicate of the focus moprh once upon initial calculation would be a nice way of meeting the problem halfway.

**Closed** 2019-12-25 13:50 UTC
