### ISSUE TITLE
Manually correcting unknown/unmature morphemes?

### ISSUE THREAD

**Issue by stanaquil** [kaegi/MorphMan#13] opened 2017-01-21 15:03 UTC
I have a question which might be more of a philosophical discussion than a feature request. Would it ever be possible to have a feature that would allow the user to manually correct what MorphMan thinks the morphemes in the sentence are? And if it is possible, is it advisable?

I realize that the whole point of MorphMan is to automate the process, so maybe trying to micro-manage it would never be a good idea. But I'm running into a fair number of cases where MorphMan does not recognize a word, and instead tries to break it down into smaller morphemes. E.g. 調弦 (to tune a stringed instrument). It thinks this word is two separate morphemes, and indeed 弦 does appear often alone in my novel, meaning stringed instrument or the string section, but 調弦 is a different word.

Another case that often comes up is names. For some reason, MorphMan sometimes recognizes the name 八坂 (Yasaka), but in other cases, inexplicably seems to think that the same combination of characters means "8 slopes" (坂 alone is treated as an unknown/unmature morpheme). 

I have noticed that most of the places where it messes up are also troublesome for Anki's auto-furigana generator. AwesomeTTS is able to guess the correct pronunciation slightly more often, but it's not perfect either.

Another use case: it seems to persistently misunderstand verb suffixes (-dasu, -komu, -kiru, etc). It tries to interpret the suffix as an independent morpheme, when in fact that compound word has a unique meaning that needs to be learned.

I've tried feeding a list of previously unrecognized words into the known.db, but it doesn't seem to make any difference. Probably makes sense, since I think the problem is arising at the mecab level.

Maybe in the long run it's best to just let it slide, but I'm OCD enough that it bugs me, and I keep wondering if there is a way to fix it. Curious to know what you think from the programmer's standpoint.

**Comment by ChangSpivey** [comment] 2017-01-21 17:05
Yes, the problem is on the mecab level. As far as I know, almost all
japanese plugins use the mecab tool in the "Japanese Plugin" so every
other plugin has the same issues.

Mecab has a dictionary so if you want to adjust the generation that
would probably the first place to look into. I'm neither an expert in
mecab nor an expert in morphological analysis, so I can't really help
you there.

I also won't provide options that are competely mecab specific, because
the main reasons for this fork is to make it language agnostic (as far
as it can get) and reduce the complexity for the user. Because this
issue can also be applied to other languages, a middle ground might be
archieved (a user written name dictionary).

For words I just ignore this issue (with automatic generation you can
always learn a other card), but names are annoying. For example the name
ちさき will be split in sentences ...ちさきが... to .../ちさ/きが/.... If I
ignore it, these will always form _two_ unknown morphmes and thus all
cards  with that name will appear later in the queue. So I usually set
these as known (shortcut K).

A pre-morphemizer filter on the sentence string and after-morphemizer
filter on the resulting morphemes both have the disadvantage that
grammatical information is lost. In some cases there might be a sentence
where a ちさ/きが split makes sense (inferred by the grammatical structure).
It again comes down to a better algorithm in mecab...


Because I also find this _very_ annoying, I'd might just implement a
(simple) filter-heuristics [with a user dictionary] that improves these
situations but worsens other (less frequent) ones. I'd love to hear if
you have any specific implementations in mind...
The current program architecture is really just something like this:


String:"....ちさきが...."    ->   getMorphemesFromExpr()  -> List:[...,
String:"ちさ", String:"きが", ...]

**Comment by stanaquil** [comment] 2017-01-21 17:22
I've been reading through the original MorphMan thread (my god, that thread is long and technical), and someone there suggested creating a user dictionary for mecab to handle names. But like you, they didn't know enough about mecab to say how to do that, and I certainly don't either.

> a (simple) filter-heuristics [with a user dictionary] that improves these
situations but worsens other (less frequent) ones.

This appeals to me. Personally, I don't pay as much attention to the parts of speech; it seems like everything I analyze is 85% nouns anyway (because suru verbs get counted as nouns), so differentiation by part of speech doesn't mean much to me. I wouldn't mind if user-selected words fell into the "unknown" part of speech category.

I only partially understand what you're saying about program architecture, but from what I do understand, it seems like a pre-morphemizer filter would make the most sense. Catch the words before mecab has a chance to deconstruct them.

The other idea that occurred to me was to allow the user to incorporate a field called something like "use THIS not this" (obviously it needs a better name!) where you could fill in what you want the morpheme on the card to be interpreted as. But that is probably far too complicated from a programming standpoint.

**Comment by ChangSpivey** [comment] 2017-01-21 18:01
> I've been reading through the original MorphMan thread (my god, that thread is long and technical), and someone there suggested creating a user dictionary for mecab to handle names. But like you, they didn't know enough about mecab to say how to do that, and I certainly don't either.

I never bothered reading through the thread. The source code is pretty informative on itself (you can even guess which iterations it went through).

> This appeals to me. Personally, I don't pay as much attention to the parts of speech; it seems like everything I analyze is 85% nouns anyway (because suru verbs get counted as nouns), so differentiation by part of speech doesn't mean much to me. I wouldn't mind if user-selected words fell into the "unknown" part of speech category. Or maybe even a "user" category.

I don't even know why there is something like that in the first place (maybe I should read the thread?). I don't really see a benefit aside from statistics. The source code indicates a 'verb bonus', but that didn't seem to work... Speech categories also complicate everything else in its way (that was a major slowdown when I tried to read the code). Even though there is such a feature available, I don't use it (am I missing something?) - in my opinion it is not worth it.

> I only partially understand what you're saying about program architecture, ....

I just meant we can operate on the string and on the resulting morpheme array and put as many layers between input and output as we like. Only the `getMorphmemesFromExpr` is a black-box.

> but from what I do understand, it seems like a pre-morphemizer filter would make the most sense. Catch the words before mecab has a chance to deconstruct them.

I see two possibilities:

- operate on the morpheme array
  - pro: mecab can figure out the sentence structure/still has all information available
  - contra: might produce morphemes that partly overlap with name (ちさきが -> ちさ/きが are two morphemes, so if we extract ちさき what do we do with が or other extra characters? Throw it away?)
 
- operate on the string, and if we encounter a user given name, evaluate the string before and after that name with the morphemizer
  -  pro: will never produce partly overlapping morphemes
  - contra: mecab will not have the full sentence, so it might result in even more errors

I'm just thinking aloud, but from these arguments I think the first heuristic is better... 

> The other idea that occurred to me was to allow the user to incorporate a field called something like "use THIS not this" (obviously it needs a better name!) where you could fill in what you want the morpheme on the card to be interpreted as. But that is probably far too complicated from a programming standpoint.

This will result in a little "spaghetti code", but it's not complicated at all! I think the potential gain is worth the cost. The only problem I see is whether this will actually improve the situation for the user... To make use of that feature you'd have to through each card with a name manually. Is this really better than setting the name morphemes as `known` and let MorphMan handle the rest? [workflow-use-case needed]

MorphMan will only skip new cards but not reviewing cards. and you can always learn (wrongly) buried cards with the `learn now (Ctrl-Shift-N)` feature. I like this idea more than a global name dictionary....

**Comment by stanaquil** [comment] 2017-01-21 18:16
Hm, well, if you did a search in anki on the problematic name/word and selected those cards, you could mass-fill a blank field with a search and replace operation, right?

The disadvantage of setting a given morpheme as "known" to get around the parsing problem is if you don't actually know it (like, you haven't learned the name yet, or you need to learn the compound word, or whatever).

I don't think I realized that the "learn now" feature existed, I'll have to experiment with that.

**Comment by stanaquil** [comment] 2017-01-21 18:22
Re: the parts of speech thing, I think that was originally there because some people wanted to be able to prioritize learning one particular part of speech (all nouns, or all adjectives, or whatever). You could also blacklist certain categories (I think the code was designed to blacklist particles, punctuation and UNKNOWN items by default). But I'm with you, I don't really understand the benefit of learning this way. Not when Japanese has so much overlap between categories as it is (nouns that are also adjectives, adjectives that are also nouns...).

**Comment by ChangSpivey** [comment] 2017-01-21 19:39
Well, I thought you meant completely bypassing the actual morphemizer if that field is non-blank. You'd have to specify every morpheme in that case.

I think your idea is worth a try, but I won't implement it this week.

**Comment by stanaquil** [comment] 2017-01-21 21:02
No problem, thanks for considering it. And thanks very much for the work that you are doing to make this useful tool more user friendly.

**Comment by kaegi** [comment] 2017-04-16 19:09
New progress on this!

The [latest development](https://github.com/kaegi/MorphMan/commit/2c13557f4d47c070a9ef0cc9bb3eeee24c62df22) version offers 'ReplaceRules' which can accomplish what you want. The relevant documentation is [here](https://github.com/kaegi/MorphMan/blob/2c13557f4d47c070a9ef0cc9bb3eeee24c62df22/morph/util.py#L95-L116). Currently you can only access them over the Anki REPL (  Ctrl+: ). You can use these commands, which set, print and save the configuration: 

```
mw.col.conf['addons']['morphman']['ReplaceRules'] = [([u'MyDrama'], u'<<.*?>>', [])]
pp(mw.col.conf['addons']['morphman']['ReplaceRules'])
mw.col.setMod()
```

I hope this will be beneficial to you, as soon as your schedule allows you to dive back into learning Japanese again (Good luck!).

**Comment by kaegi** [comment] 2017-08-27 09:58
Because correcting morphemes manually is now possible (see last post), I'm going to close this issue.

**Closed by kaegi** 2017-08-27 09:58 UTC
