### ISSUE TITLE
unmodified models getting cards cyclically buried

### ISSUE THREAD

**Issue by rfglenn** [kaegi/MorphMan#11] opened 2017-01-19 07:05 UTC
I'd previously been using an older version of morphman, but updated ~today to the newer version with gui. A few hours after setting it up, I found that I wasn't able to study new cards of a certain model in one deck: I would see that I had _n_ new cards; when I attempted to study the new cards, they would instead all become buried. Un-burying the cards restarted the cycle. 

Exporting the deck and importing it on another machine that did not have the morphman plugin caused the expected behavior to occur (that is, being able to study the new cards).
Exporting the deck and importing it on another machine that did have morphman (with the same settings) caused the bury-cycle.
Removing the morphman plugin from my machine allowed me to study the new cards; re-adding the plugin broke them again. 
When I added new cards to that deck from a different model (that morphman did not analyze or modify), those cards were able to be studied; new cards from models that morphman analyzed but did not modify could not be studied.
Changing the model from being unmodified by morphman to being modified by morphman did allow me to view the new cards.

So it seems to be isolated to morphman; I'm not really sure how to figure out exactly what is causing it, other than making the deck be modified seems to have fixed it. I have it reproduced on a test machine, so I can give more information if I know what to do.

**Comment by ChangSpivey** [comment] 2017-01-19 09:15
If all vocab from a deck is contained in the db as mature (caused by wrong settings at one point etc.), these cards are skipped. So check/try to delete the MorphMan database under `Documents/Anki/YourUser/dbs` and regenerate it.

If that does not fix the problem, please post your morphemizer and target language for debugging purposes here.

This issue might be related to https://github.com/ChangSpivey/MorphMan/issues/8.

**Comment by rfglenn** [comment] 2017-01-19 18:02
I'm certain at least some of the cards to be studied contained unknown vocab. When I above said that I was able to study new cards after allowing morphman to modify the model, I spoke a little soon, because it seems that some of the new cards were buried for only having mature vocab. (Which is the expected behavior, I think, just not desired for this case; I really do want to see every card from this deck, though I do want its contents analyzed for the purposes of generating my known morphemes)

Deleting the databases, resetting the preferences to as they were before (this model unmodified, all the rest modified), and regenerating the databases seems to yield the same bury-loop.

Target language is japanese; the morphemizer is the default japanese one.

**Comment by ChangSpivey** [comment] 2017-01-19 18:28
Yes, I now see what you mean... A fix is now available in the `disable-skipping` branch:

https://github.com/ChangSpivey/MorphMan/tree/disable-skipping

Download on main page via `Clone or download -> Download ZIP` and then install like normal. Please let me know whether it works for you, so I can include it in the official version.

**Comment by rfglenn** [comment] 2017-01-19 18:54
Replacing the old version of morphman with that one seems to work perfectly on both machines, at least with regards to this issue. I'll let you know if later I see any bugs with it. Thanks!

**Comment by stanaquil** [comment] 2017-01-20 16:47
Just wanted to note for the record that I seem to be having the same problem (new sentences getting buried too often). I'm using the dev version that allows syncing between platforms, so I won't download the branch for now, but it seems like it would be good to offer an option in the gui to let the user turn this behavior on and off, at some point in the future.

**Comment by ChangSpivey** [comment] 2017-01-20 17:36
I think `modify=no` should always imply that skipping is turned off (do you have any use case where you want an unoptimized card order but skip through the first "bad" ones?).

The problem I struggle with is where to put that option for `modify=yes` conceptionally.

-  as filter option
   -  pro: fine grained control
   -  con: clutters the interface (the note filter table is already big as it is)
-  as general option (influencing all filters at once)
   - pro: no clutter, one checkbox on a `General Options` page is sufficient
   - con: you can't learn all cards in one deck and skip cards in others....

I'd love to hear your ideas about it!

**Comment by stanaquil** [comment] 2017-01-20 18:53
Hm, maybe I'm still getting used to wrapping my head around how the add-on works. I don't want to set modify to no, because I like that having "modify on" results in my getting the optimal card first. What puzzles me is when "modify" results in it refusing to give me any new cards at all.

My scenario is this: I have a model called "Japanese(recognition)" which I use for any situation where I want the card to give me a sentence with kanji that I need to be able to read and fully understand. Right now, this model is used in two different decks. One is a deck with thousands of sentences I imported from a novel I'm reading (perfect candidate to have MorphMan prioritize the sentences for me, and if it buries some, that's fine). The second is my existing Sentence deck, to which I occasionally add new sentences when I am having a problem with a particular word. I want to see all the new sentences I add to the Sentence deck right away no matter what. I find it baffling when 15 or 20 sentences sit in the queue day after day because MorphMan thinks they should be buried.

From what you're saying, maybe I should use separate card models and turn modify off for one of them. That would fix my problem simply enough. Or I could just be patient and wait until MorphMan decides to un-bury sentences on its own.

Do prioritizing cards with un-mature morphemes and skipping (burying) cards that are too similar to other cards always have to go hand in hand? Maybe that's how the software is written - I was thinking of them as potentially two separate operations.

At lot of this is just me thinking aloud, don't know if it will help.

**Comment by ChangSpivey** [comment] 2017-01-20 20:58
> The second is my existing Sentence deck, to which I occasionally add new sentences when I am having a problem with a particular word. I want to see all the new sentences I add to the Sentence deck right away no matter what. I find it baffling when 15 or 20 sentences sit in the queue day after day because MorphMan thinks they should be buried.

In that case there is no need for MorphMan. You have a note type/__tag__ filter in the preferences, so if you tag your novel cards with `novel` and set it in the preferences, you should be good.

> Or I could just be patient and wait until MorphMan decides to un-bury sentences on its own.

It will never do that. See next paragraph.

> What puzzles me is when "modify" results in it refusing to give me any new cards at all.

I'm maybe saying things that you already know, but this is how MorphMan works:

- a card has certain morphemes
- morphmes go from `unknown` -> `unmature` -> `known/mature`
- each 
- 

> Do prioritizing cards with un-mature morphemes and skipping (burying) cards that are too similar to other cards always have to go hand in hand? Maybe that's how the software is written - I was thinking of them as potentially two separate operations.

**Comment by stanaquil** [comment] 2017-01-20 21:07
I think you might be in the process of editing your comment above, so I'll check back again in a bit, but to clarify:

In my Sentences deck, all of the buried cards have words that are Unmature (I just double checked this). It just doesn't want to show them to me yet, probably because I recently worked on another card with the same Unmature word. If I try to unbury them in anki, it immediately re-buries them again. Is this the intended behavior, or am I missing something obvious?

Thanks for the tag reminder, I hadn't thought of that, and it would certainly help.

**Comment by ChangSpivey** [comment] 2017-01-20 21:22
See #12, this bug is different from the one from the OP.

**Comment by stanaquil** [comment] 2017-01-20 22:27
>I'm maybe saying things that you already know, but this is how MorphMan works:

Thank you for explaining and pointing to the relevant bits of code, actually there is quite a lot I don't understand about how this tool works - I am trying to read up on it now. I may end up learning some python at this rate.

**Comment by gnprice** [comment] 2017-02-05 05:14
@kaegi , is this issue resolved now? It looks like the commit at the tip of https://github.com/kaegi/MorphMan/commits/disable-skipping has landed in master (as https://github.com/kaegi/MorphMan/commit/7f644a192 ).

**Comment by kaegi** [comment] 2017-02-05 05:50
Theoretically it should be, and I haven't heard any complaining, so I will close this issue.

**Closed by kaegi** 2017-02-05 05:50 UTC
