### ISSUE TITLE
Doesnt open on 2.1.55 QT5 or QT6

### ISSUE THREAD

**Issue by rltim151** [kaegi/MorphMan#281] opened 2023-01-03 08:12 UTC
起動中にエラーが発生しました： ⁨Traceback (most recent call last):   File "aqt.main", line 179, in __init__   File "aqt.main", line 228, in finish_ui_setup   File "aqt.toolbar", line 48, in draw   File "aqt.toolbar", line 133, in _centerLinks   File "_aqt.hooks", line 4720, in __call__   File "C:\Users\MSI\AppData\Roaming\Anki2\addons21\1032435232\morph\stats.py", line 69, in on_top_toolbar_did_init_links     name, details = getStatsLink()   File "C:\Users\MSI\AppData\Roaming\Anki2\addons21\1032435232\morph\stats.py", line 52, in getStatsLink     d = loadStats()   File "C:\Users\MSI\AppData\Roaming\Anki2\addons21\1032435232\morph\stats.py", line 19, in loadStats     f = gzip.open(getStatsPath())   File "C:\Users\MSI\AppData\Roaming\Anki2\addons21\1032435232\morph\stats.py", line 14, in getStatsPath     def getStatsPath(): return cfg('path_stats')   File "C:\Users\MSI\AppData\Roaming\Anki2\addons21\1032435232\morph\preferences.py", line 26, in get_preference     return _get_config_py_preference(key, model_id, deck_id)   File "C:\Users\MSI\AppData\Roaming\Anki2\addons21\1032435232\morph\preferences.py", line 71, in _get_config_py_preference     if key in config_py.deck_overrides.get(deck, []): AttributeError: 'NoneType' object has no attribute 'deck_overrides' ⁩

**Comment by Vilhelm-Ian** [comment] 2023-01-03 09:38
@rltim151 it works with the following pull request https://github.com/rameauv/MorphMan . to install it go to your addon floder copy the above url and just do git clone https://github.com/rameauv/MorphMan

**Comment by rltim151** [comment] 2023-01-09 06:23
Ok will do it thanks

**Comment by landonepps** [comment] 2023-01-10 19:43
Closing as duplicate of #269

**Closed by landonepps** 2023-01-10 19:43 UTC
