### ISSUE TITLE
Recalc fails out of nowhere.

### ISSUE THREAD

**Issue by cindsa** [kaegi/MorphMan#209] opened 2020-12-02 14:06 UTC
For some reason (sometimes?) it starts giving out an error during all.db recalc. Seems like it can't process some notes for some reason? Since sometimes deleting the sentences mentioned in the log fixes it. But then today it just started giving errors on a lot of new sentences, even though previously it recalc'd them just fine. 
The error in question:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-02 00:50:34

Caught exception:
Traceback (most recent call last):
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('ハードさんが私に感じ取っているものは恐らく幻だろうけど、とにかくハードさんの傲慢は私には苛烈過ぎる',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 41, in __call__
    return self.cache[args]
KeyError: ('ハードさんが私に感じ取っているものは恐らく幻だろうけど、とにかくハードさんの傲慢は私には苛烈過ぎる',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\__init__.py", line 14, in onMorphManRecalc
    main.main()
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 434, in main
    allDb = mkAllDb(cur)
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 128, in mkAllDb
    ms = getMorphemes(morphemizer, fieldValue, ts)
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\morphemes.py", line 165, in getMorphemes
    ms = morphemizer.getMorphemesFromExpr(expression)
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\morphemizer.py", line 68, in getMorphemesFromExpr
    return getMorphemesMecab(expression)
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 86, in getMorphemesMecab
    ms = [getMorpheme(m.split('\t')) for m in interact(e).split('\r')]
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\util_external.py", line 43, in __call__
    value = self.func(*args)
  File "C:\Users\kahinochi\AppData\Roaming\Anki2\addons21\900801631\morph\mecab_wrapper.py", line 223, in interact
    p.stdin.flush()
OSError: [Errno 22] Invalid argument

**Comment by ianki** [comment] 2020-12-08 05:49
Are you able to update to the latest version with Anki 2.1.35?  All of the recent fixes have gone into that version.

**Comment by cindsa** [comment] 2020-12-08 08:45
Not at the moment since mia/migaku plugins haven't been updated to 2.1.35 yet it seems and I really need those too.

**Comment by ianki** [comment] 2020-12-08 17:09
The 2.1.35 versions are available on the Migaku Patreon, but apparently should be public soon.

The error you're getting may be related to the dictionary you're using.  Do you have the 'MeCab UniDic Japanese Dictionary' add-on installed?

**Comment by cindsa** [comment] 2020-12-08 19:17
Yes I do have the mecab add on installed.

**Comment by ianki** [comment] 2020-12-17 16:35
I think this is caused by having "bad" control characters in some cards.  Once that error happens in MecCab you may start getting the same error on other cards too until a re-start.  I have a patch to fix this.

**Comment by ianki** [comment] 2020-12-24 16:29
This is fixed in #214 and should be available in the next update.

**Closed by ianki** 2020-12-24 16:29 UTC
